# Generated by Django 5.0.6 on 2024-06-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_form_contact_user_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='media/default', upload_to='users/%Y/%m/%d/'),
        ),
    ]
